function GetTriplets(pkgs){
    let s = '';
    for(const name of pkgs){
        s += `${name}:x86-windows ${name}:x64-windows `;
    }
    return s;
}

function GetExportScript(pkgs, type = '--raw'){
    return `./vcpkg.exe export ${GetTriplets(pkgs)} ${type}`;
}

function GetInstallScript(pkgs){
    return `./vcpkg.exe install ${GetTriplets(pkgs)}`;
}

const allPkgs = [
'7zip',//                                   19.00            Library for archiving file with a high compressi...
'berkeleydb',//                             4.8.30-3         BDB - A high-performance embedded database for key/value data.
'curl',//                                   7.66.0-1         A library for transferring data with URLs
'cxxopts',//                                2.2.0            This is a lightweight C++ option parser library,...
'directxtex',//                             oct2019          DirectXTex texture processing library
'eigen3',//                                 3.3.7-3          C++ template library for linear algebra: matrice...
'ffmpeg',//                                 3.3.7-3          C++ template library for linear algebra: matrice...
'freeimage',//                              3.18.0-7         Support library for graphics image formats
'glog',//                                   0.4.0-2          C++ implementation of the Google logging module
'jsoncpp',//                                1.9.1            jsoncpp is an implementation of a JSON reader an...
'leveldb',//                                1.22-1           LevelDB is a fast key-value storage library writ...
'libjpeg-turbo',//                          2.0.3            libjpeg-turbo is a JPEG image codec that uses SI...
'md5',//                                    1.0.0            MD5 C++ class convert from Frank Thilo (thilo@un...
'mongoose',//                               6.15-1           Embedded web server / embedded networking library
'openal-soft',//                            1.19.1-2         OpenAL Soft is an LGPL-licensed, cross-platform,...
'openvr',//                                 1.5.17           an API and runtime that allows access to VR hard...
'poly2tri',//                               1.0.0            2D constrained Delaunay triangulation library
'portaudio',//                              2019-11-5        PortAudio Portable Cross-platform Audio I/O API ...
'sqlite3',//                                3.30.1-1         SQLite is a software library that implements a s...
'tinyxml',//                                2.6.2-4          A simple, small, minimal, C++ XML parser that ca...
'vcglib',//                                 1.0.1            library for manipulation, processing, cleaning, ...
'zlib',//                                   1.2.11-5         A compression library
];

//console.log(GetInstallScript(toInstall));
console.log(GetExportScript(allPkgs));