function GetTriplets(pkgs){
    let s = '';
    for(const name of pkgs){
        s += `${name}:x86-windows ${name}:x64-windows `;
    }
    return s;
}

function GetExportScript(pkgs, type = '--raw'){
    return `./vcpkg.exe export ${GetTriplets(pkgs)} ${type}`;
}

function GetInstallScript(pkgs){
    return `./vcpkg.exe install ${GetTriplets(pkgs)}`;
}

const allPkgs = [
'7zip',//                                   19.00            Library for archiving file with a high compressi...
'curl',//                                   7.66.0-1         A library for transferring data with URLs
'cxxopts',//                                2.2.0            This is a lightweight C++ option parser library,...
'directxtex',//                             oct2019          DirectXTex texture processing library
'eigen3',//                                 3.3.7-3          C++ template library for linear algebra: matrice...
'ffmpeg',//                                 3.3.7-3          C++ template library for linear algebra: matrice...
'freeglut',//                               3.0.0-7          Open source implementation of GLUT with source a...
'freeimage',//                              3.18.0-7         Support library for graphics image formats
'giflib',//                                 5.1.4-3          A library for reading and writing gif images.
'jasper',//                                 2.0.16-2         Open source implementation of the JPEG-2000 Part...
'jsoncpp',//                                1.9.1            jsoncpp is an implementation of a JSON reader an...
'jxrlib',//                                 2019.10.9        Open source implementation of the jpegxr image f...
'lcms',//                                   2.9-1            Little CMS.
'libjpeg-turbo',//                          2.0.3            libjpeg-turbo is a JPEG image codec that uses SI...
'liblzma',//                                5.2.4-2          Compression library with an API similar to that ...
'libpng',//                                 1.6.37-5         libpng is a library implementing an interface fo...
'libraw',//                                 201903-2         raw image decoder library
'libwebp',//                                1.0.2-7          Lossy compression of digital photographic images.
'mongoose',//                               6.15-1           Embedded web server / embedded networking library
'openal-soft',//                            1.19.1-2         OpenAL Soft is an LGPL-licensed, cross-platform,...
'openexr',//                                2.3.0-4          OpenEXR is a high dynamic-range (HDR) image file...
'openjpeg',//                               2.3.1-1          JPEG 2000 image library
'openvr',//                                 1.5.17           an API and runtime that allows access to VR hard...
'portaudio',//                              2019-11-5        PortAudio Portable Cross-platform Audio I/O API ...
'sdl1',//                                   1.2.15-8         Simple DirectMedia Layer is a cross-platform dev...
'sqlite3',//                                3.30.1-1         SQLite is a software library that implements a s...
'szip',//                                   2.1.1-6          Szip compression software, providing lossless co...
'tiff',//                                   4.0.10-8         A library that supports the manipulation of TIFF...
'tinyxml2',//                               7.0.1-2          A simple, small, efficient, C++ XML parser
'tinyxml',//                                2.6.2-4          A simple, small, minimal, C++ XML parser that ca...
'vcglib',//                                 1.0.1            library for manipulation, processing, cleaning, ...
'zlib',//                                   1.2.11-5         A compression library
];

//console.log(GetInstallScript(toInstall));
console.log(GetExportScript(allPkgs));